// <auto-generated />
using ApiPessoas.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiPessoas.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiPessoas.Model.Pessoa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("Documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Telefone");

                    b.Property<int>("TipoFuncao")
                        .HasColumnType("int")
                        .HasColumnName("TipoFuncao");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int")
                        .HasColumnName("TipoPessoa");

                    b.HasKey("Id");

                    b.ToTable("PessoaTb");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Documento = "00000000000",
                            Email = "bruce@email.com",
                            Endereco = "Gotham City",
                            Nome = "Bruce Wayne",
                            Telefone = "1140028921",
                            TipoFuncao = 0,
                            TipoPessoa = 0
                        },
                        new
                        {
                            Id = 2L,
                            Documento = "00000000000001",
                            Email = "industrueswayne@email.com",
                            Endereco = "Gotham City",
                            Nome = "Industrias Wayne",
                            Telefone = "1140028922",
                            TipoFuncao = 1,
                            TipoPessoa = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
